[package]
authors = ["The Rust Project Developers"]
name = "rustc_data_structures"
version = "0.0.0"

[lib]
name = "rustc_data_structures"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
ena = "0.7.1"
log = "0.3"
serialize = { path = "../libserialize" }
