[package]
authors = ["The Rust Project Developers"]
name = "rustc_mir"
version = "0.0.0"

[lib]
name = "rustc_mir"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
arena = { path = "../libarena" }
bitflags = "1.0"
graphviz = { path = "../libgraphviz" }
log = "0.4"
log_settings = "0.1.1"
rustc = { path = "../librustc" }
rustc_back = { path = "../librustc_back" }
rustc_const_math = { path = "../librustc_const_math" }
rustc_data_structures = { path = "../librustc_data_structures" }
rustc_errors = { path = "../librustc_errors" }
serialize = { path = "../libserialize" }
syntax = { path = "../libsyntax" }
syntax_pos = { path = "../libsyntax_pos" }
byteorder = { version = "1.1", features = ["i128"] }
rustc_apfloat = { path = "../librustc_apfloat" }
abomonation = "0.5.0"
abomonation_derive = "0.3.0"
crossbeam = "0.3.2"

[dependencies.differential-dataflow]
git = "https://github.com/frankmcsherry/differential-dataflow.git"
default-features = false

[dependencies.timely]
git = "https://github.com/frankmcsherry/timely-dataflow"
default-features = false
